name: Pipeline on Commits
on:
  push:
    branches:
      - main # specify the branch name for which the pipeline should be triggered

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Define other steps for the pipeline as needed

